import { ScrollView } from "std-widgets.slint";
import { DatabaseModel } from "../models/database-model.slint";
import { DatabaseItem } from "database-item.slint";
import { AppColors } from "../../../tokens/app-colors.slint";
import { AppRadius } from "../../../tokens/app-radius.slint";
import { AppSpacings } from "../../../tokens/app-spacing.slint";

export component DatabaseExplorer inherits Rectangle {
    in property <[DatabaseModel]> databases;

    background: AppColors.surface;
    border-radius: AppRadius.default;
    border-width: AppSpacings.border-width;
    border-color: AppColors.border;
    clip: true;

    ScrollView {
        VerticalLayout {
            padding: AppSpacings.small;
            spacing: 0;
            alignment: start;

            for database in root.databases: DatabaseItem {
                title: database.name;
                level: 0;

                for schema in database.schemas: DatabaseItem {
                    title: schema.name;
                    level: 1;

                    for table in schema.tables: DatabaseItem {
                        title: table.name;
                        level: 2;

                        for column in table.columns: DatabaseItem {
                            title: column.name;
                            level: 3;
                        }
                    }
                }
            }
        }
    }
}
