import { Sidebar } from "sidebar.slint";
import { MainArea } from "main-area.slint";
import { RadiusTokens, SpacingTokens } from "../tokens/spacing-tokens.slint";
import { ColorTokens } from "../tokens/colors-tokens.slint";
export component AppFrame inherits Rectangle {
    background: transparent;
    // border-width: 1px;
    // border-color: ColorTokens.border;
    // border-radius: RadiusTokens.large;

    HorizontalLayout {
        padding-top: SpacingTokens.large;
        padding-bottom: SpacingTokens.large;
        // padding-left: SpacingTokens.large;
        padding-right: SpacingTokens.large;

        // spacing: SpacingTokens.medium;
        MainArea {
            // width: 100%;
            // height: 100%;
            horizontal-stretch: 1;
            vertical-stretch: 1;
        }
    }
}
