import { AboutSlint, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ColorTokens } from "../tokens/colors-tokens.slint";
import { SpacingTokens, RadiusTokens } from "../tokens/spacing-tokens.slint";
import { HorizontalSplitter } from "horizontal-splitter.slint";
import { VerticalSplitter } from "vertical-splitter.slint";

export component MainArea inherits Rectangle {
    in-out property <length> panel-width: 240px;
    in-out property <length> editor-height: 400px;

    HorizontalLayout {
        // padding: SpacingTokens.medium;
        padding-top: SpacingTokens.large;
        spacing: 0;

        // panel
        Rectangle {
            width: root.panel-width;
            border-radius: RadiusTokens.large;
            background: ColorTokens.surface;
        }

        HorizontalSplitter {
            moved-by(delta) => {
                root.panel-width = max(
                    180px,
                    min(
                        500px,
                        root.panel-width + delta));
            }
        }

        // Workspace
        VerticalLayout {
            horizontal-stretch: 1;
            // spacing: SpacingTokens.medium;

            // padding-bottom: SpacingTokens.medium;
            // padding-right: SpacingTokens.medium;

            // isso vai ser o editor
            Rectangle {
                preferred-height: root.editor-height;
                min-height: 150px;
                border-radius: RadiusTokens.large;
                background: ColorTokens.surface;
            }

            // Splitter
            VerticalSplitter {
                moved-by(delta) => {
                    root.editor-height = max(
                        150px,
                        root.editor-height + delta);
                }
            }

            // e o console
            Rectangle {
                vertical-stretch: 1;
                min-height: 80px;
                border-radius: RadiusTokens.large;
                background: ColorTokens.surface;
            }
        }
    }
}
