import { AppColors } from "../tokens/app-colors.slint";
export component VerticalSplitter inherits TouchArea {
    height: 6px;
    mouse-cursor: ns-resize;

    Rectangle {
        width: 100%;
        height: 1px;
        y: (parent.height - self.height) / 2;
        background: transparent;
    }

    callback moved-by(length);

    moved => {
        if (self.pressed) {
            root.moved-by(self.mouse-y - self.pressed-y);
        }
    }
}
