export global ColorTokens {
    // Backgrounds
    out property <color> background: #1E1E21;
    out property <color> panel:#252529;
    out property <color> surface: #2B2B30;
    out property <color> surface-hover: #29292d;
    out property <color> surface-selected: #303035;
    out property <color> icons: #f0f0f0;

    // Borders
    out property <color> border:  #3A3A40;
    out property <color> border-subtle: #29292d;

    // Text
    out property <color> text-primary: #f4f4f5;
    out property <color> text-secondary: #a1a1aa;
    out property <color> text-muted: #71717a;

    // Accent
    out property <color> accent: #9c00f6;
}
