export global SpacingTokens {
    out property <length> border-width: 1px;
    out property <length> extra-small: 4px;
    out property <length> small: 8px;
    out property <length> medium: 12px;
    out property <length> large: 16px;
    out property <length> extraLarge: 24px;
    out property <length> extraExtraLarge: 36px;
}

export global RadiusTokens {
    out property <length> small: 8px;
    out property <length> medium: 16px;
    out property <length> large: 24px;
    out property <length> extraLarge: 32px;
    out property <length> giant: 48px;
}
