/// Scalar functions available in every supported dialect.
pub const ANSI_FUNCTIONS: &[&str] = &[
    "ABS",
    "AVG",
    "CAST",
    "CEIL",
    "CEILING",
    "CHAR_LENGTH",
    "COALESCE",
    "CONCAT",
    "COUNT",
    "FLOOR",
    "GREATEST",
    "LEAST",
    "LENGTH",
    "LOWER",
    "LTRIM",
    "MAX",
    "MIN",
    "MOD",
    "NULLIF",
    "POSITION",
    "POWER",
    "ROUND",
    "RTRIM",
    "SUBSTRING",
    "SUM",
    "TRIM",
    "UPPER",
];

/// Functions PostgreSQL adds on top of the shared list.
pub const POSTGRES_FUNCTIONS: &[&str] = &[
    "AGE",
    "ARRAY_AGG",
    "BOOL_AND",
    "BOOL_OR",
    "DATE_PART",
    "DATE_TRUNC",
    "ENCODE",
    "EXTRACT",
    "GENERATE_SERIES",
    "JSON_AGG",
    "JSONB_AGG",
    "JSONB_BUILD_OBJECT",
    "MD5",
    "NOW",
    "PERCENTILE_CONT",
    "PERCENTILE_DISC",
    "RANDOM",
    "ROW_NUMBER",
    "SETSEED",
    "STRING_AGG",
    "TO_CHAR",
    "TO_DATE",
    "TO_NUMBER",
    "TO_TIMESTAMP",
    "UNNEST",
    "XMLELEMENT",
];

/// Functions MySQL adds on top of the shared list.
pub const MYSQL_FUNCTIONS: &[&str] = &[
    "CONCAT_WS",
    "CURDATE",
    "CURTIME",
    "DATE_ADD",
    "DATE_FORMAT",
    "DATE_SUB",
    "DATEDIFF",
    "DAY",
    "DAYOFMONTH",
    "GROUP_CONCAT",
    "IF",
    "IFNULL",
    "INSTR",
    "JSON_EXTRACT",
    "JSON_UNQUOTE",
    "LAST_INSERT_ID",
    "LOCATE",
    "MONTH",
    "NOW",
    "REGEXP_LIKE",
    "STR_TO_DATE",
    "SUBSTRING_INDEX",
    "UNIX_TIMESTAMP",
    "UUID",
    "YEAR",
];

/// Functions SQLite adds on top of the shared list.
pub const SQLITE_FUNCTIONS: &[&str] = &[
    "CHANGES",
    "DATE",
    "DATETIME",
    "IFNULL",
    "INSTR",
    "JULIANDAY",
    "LAST_INSERT_ROWID",
    "LIKELIHOOD",
    "LIKELY",
    "PRINTF",
    "QUOTE",
    "RANDOMBLOB",
    "STRFTIME",
    "TIME",
    "TOTAL",
    "TYPEOF",
    "UNLIKELY",
    "ZEROBLOB",
];

/// Functions Firebird adds on top of the shared list.
pub const FIREBIRD_FUNCTIONS: &[&str] = &[
    "BIT_LENGTH",
    "CHAR_LENGTH",
    "CURRENT_CONNECTION",
    "CURRENT_ROLE",
    "CURRENT_TRANSACTION",
    "GEN_ID",
    "IIF",
    "ISNULL",
    "OCTET_LENGTH",
    "RDB$GET_CONTEXT",
    "RDB$SET_CONTEXT",
    "SLEEP",
    "TRANSLATE",
    "TRUNC",
];
